package crypto

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"github.com/arifai/go-modular-monolithic/pkg/errormessage"
	"golang.org/x/crypto/argon2"
	"log"
	"strings"
)

// Argon2IdHash is the struct for GenerateHash and VerifyHash
type Argon2IdHash struct {
	Time    uint32
	Memory  uint32
	Threads uint8
	KeyLen  uint32
	SaltLen uint32
}

// DefaultArgon2IDHash is an instance of crypto.Argon2IdHash used to configure Argon2ID password hashing with specified time,
// memory, threads, key length, and salt length.
var DefaultArgon2IDHash = &Argon2IdHash{Time: 3, Memory: 64 * 1024, Threads: 4, KeyLen: 32, SaltLen: 32}

// GenerateHash generates a password hash using the Argon2ID algorithm and given salt. Returns the encoded hash or an error.
func (a *Argon2IdHash) GenerateHash(password, salt []byte) (string, error) {
	var err error

	if len(salt) > 0 && uint32(len(salt)) != a.SaltLen {
		log.Printf("salt length is incorrect: expected %d bytes, got %d bytes", a.SaltLen, len(salt))
		return "", err
	}

	if len(salt) == 0 {
		salt, err = generateBytes(a.SaltLen)
		if err != nil {
			return "", err
		}
	}

	hash := argon2.IDKey(password, salt, a.Time, a.Memory, a.Threads, a.KeyLen)
	base64Salt := base64.StdEncoding.EncodeToString(salt)
	base64Hash := base64.StdEncoding.EncodeToString(hash)
	encodedHash := fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s", argon2.Version, a.Memory, a.Time, a.Threads, base64Salt, base64Hash)

	return encodedHash, nil
}

// VerifyHash compares a password with its encoded hash to check for validity.
// It returns true if the password matches the hash, false otherwise. If an error occurs during the process,
// it returns false and the error.
func VerifyHash(password, encodedHash string) (bool, error) {
	a, salt, hash, err := decodeHash(encodedHash)
	if err != nil {
		return false, err
	}

	otherHash := argon2.IDKey([]byte(password), salt, a.Time, a.Memory, a.Threads, a.KeyLen)

	if subtle.ConstantTimeCompare(hash, otherHash) == 1 {
		return true, nil
	}

	return false, nil
}

// generateBytes generates a slice of random bytes with the specified length.
// Returns the generated bytes or an error if any.
func generateBytes(length uint32) ([]byte, error) {
	secret := make([]byte, length)
	_, err := rand.Read(secret)
	if err != nil {
		return nil, err
	}

	return secret, nil
}

// decodeHash decodes an encoded Argon2ID hash string into its components: Argon2IdHash struct, salt, and hash.
// It returns an error if the encoded string is invalid or incompatible.
func decodeHash(encodedHash string) (a *Argon2IdHash, salt, hash []byte, err error) {
	value := strings.Split(encodedHash, "$")
	if len(value) != 6 {
		return nil, nil, nil, errormessage.ErrInvalidEncodedHash
	}

	var version int
	_, err = fmt.Sscanf(value[2], "v=%d", &version)
	if err != nil {
		return nil, nil, nil, errormessage.ErrIncompatibleArgon2Version
	}

	a = &Argon2IdHash{}
	_, err = fmt.Sscanf(value[3], "m=%d,t=%d,p=%d", &a.Memory, &a.Time, &a.Threads)
	if err != nil {
		return nil, nil, nil, err
	}

	salt, err = base64.StdEncoding.DecodeString(value[4])
	if err != nil {
		return nil, nil, nil, err
	}

	a.SaltLen = uint32(len(salt))
	hash, err = base64.StdEncoding.DecodeString(value[5])
	if err != nil {
		return nil, nil, nil, err
	}

	a.KeyLen = uint32(len(hash))

	return a, salt, hash, nil
}
