// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package common

import (
	"github.com/arifai/zenith/pkg/common"
)

// Injectors from wire.go:

func ProvideResponse() *common.Response {
	response := common.NewResponse()
	return response
}
