// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

import (
	"github.com/arifai/zenith/internal/repository"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func ProvideRepository(db *gorm.DB, rdb *redis.Client) *repository.Repository {
	repositoryRepository := repository.New(db, rdb)
	return repositoryRepository
}

func ProvideAccountRepository(db *gorm.DB, rdb *redis.Client) repository.AccountRepository {
	repositoryRepository := repository.New(db, rdb)
	accountRepository := repository.NewAccountRepository(repositoryRepository)
	return accountRepository
}

func ProvideNotificationRepository(db *gorm.DB, rdb *redis.Client) repository.NotificationRepository {
	repositoryRepository := repository.New(db, rdb)
	notificationRepository := repository.NewNotificationRepository(repositoryRepository)
	return notificationRepository
}
