// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middleware

import (
	"github.com/arifai/zenith/internal/middleware"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func ProvideStrictAuthMiddleware(db *gorm.DB, rdb *redis.Client) *middleware.StrictAuthMiddleware {
	middlewareMiddleware := middleware.New(db, rdb)
	strictAuthMiddleware := middleware.NewStrictAuthMiddleware(middlewareMiddleware)
	return strictAuthMiddleware
}
