// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package firebase

import (
	"github.com/arifai/zenith/pkg/firebase"
)

// Injectors from gin.go:

func ProvideFirebase(file string) (*firebase.Messaging, error) {
	messaging, err := firebase.New(file)
	if err != nil {
		return nil, err
	}
	return messaging, nil
}

func ProvideFirebaseMessagingService(file string) (*firebase.MessagingService, error) {
	messaging, err := ProvideFirebase(file)
	if err != nil {
		return nil, err
	}
	messagingService := firebase.NewMessagingService(messaging)
	return messagingService, nil
}
