// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/arifai/zenith/config"
)

// Injectors from gin.go:

func ProvideConfig(filenames ...string) *config.Config {
	configConfig := config.NewConfig(filenames...)
	return configConfig
}
