// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/arifai/zenith/cmd/wire/handler"
	"github.com/arifai/zenith/config"
	"github.com/arifai/zenith/internal/middleware"
	"github.com/arifai/zenith/pkg/server/http"
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRouter(db *gorm.DB, redis2 *redis.Client, cfg *config.Config) *gin.Engine {
	accountHandler := handler.ProvideAccountHandler(db, redis2, cfg)
	notificationHandler := handler.ProvideNotificationHandler(db, redis2, cfg)
	middlewareMiddleware := middleware.New(db, redis2)
	strictAuthMiddleware := middleware.NewStrictAuthMiddleware(middlewareMiddleware)
	engine := http.ProvideGinEngine(accountHandler, notificationHandler, strictAuthMiddleware)
	return engine
}
